#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#home:
#    path: /
#    controller: App\Controller\HomeController::index
#biens.index:
#    path: /biens
#    controller: App\Controller\BiensController::index

#biens.show:
#   path: /biens/{slug}-{id}
#  controller: App\Controller\BiensController::show


