#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
biens:
    path: /bien
    controller: App\Controller\BiensController::index


